[[constraint]]
  name = "github.com/pulumi/pulumi"
  branch = "master"

[[constraint]]
  name = "github.com/pulumi/pulumi-terraform"
  branch = "master"

[[constraint]]
  name = "github.com/terraform-providers/terraform-provider-openstack"
  version = "v1.16.0"

  [constraint.metadata]
    gomod-override = true
    gomod-exclude-prefixes = [
      "github.com/golang/protobuf",
    ]
